---
ansible-navigator:
  ansible:
    config:
      path: ./ansible.cfg
  execution-environment:
    image: quay.io/tmichett/travis_do374:1.0
    pull:
      policy: missing
  mode: stdout
  playbook-artifact:
    enable: false
